name: infrastructure

networks:
  infra:
    name: infra

volumes:
  runner_data:
  registry_data:
  vaultwarden_data:
  db_data:
  decrypted_secrets:
    name: decrypted_secrets

services:
  runner:
    build:
      context: runner
    image: runner:local
    container_name: github-runner
    restart: unless-stopped
    env_file:
      - secrets/runner/.env
    environment:
      - INFRA_DIR=${INFRA_DIR:?run compose.sh, not compose directly}
      - SOPS_DIR=${SOPS_DIR:?run compose.sh, not compose directly}
    security_opt:
      - label=disable
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/runner:/tmp/runner
      - runner_data:/runner/data
      - ./secrets/runner/config.json:/runner/data/.docker/config.json:ro
      - decrypted_secrets:/decrypted_secrets
      - ${INFRA_DIR}:${INFRA_DIR}
    networks:
      - infra

  registry:
    image: registry:2
    container_name: registry
    restart: unless-stopped
    env_file:
      - secrets/registry/.env
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - registry_data:/var/lib/registry
      - ./secrets/registry/.htpasswd:/auth/htpasswd:ro
    networks:
      - infra

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/confs:/etc/nginx/sites-enabled:ro
      - ./nginx/snippets:/etc/nginx/snippets:ro
      - ./secrets/nginx:/etc/ssl/cybr.club:ro
    networks:
      - infra

  postgres:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped
    env_file:
      - secrets/postgres/.env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - infra

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    env_file:
      - "secrets/vaultwarden/.env"
    volumes:
      - vaultwarden_data:/data
    networks:
      - infra
