server {
  include snippets/tls.conf;
  include snippets/docker_resolver.conf;
  server_name auth.cybr.club;

  location / {
    include snippets/proxy_headers.conf;
    set $upstream dex;
    proxy_pass http://$upstream:5556;
  }
}
