server {
  include snippets/tls.conf;
  server_name cybr.club www.cybr.club;

  root /var/www/revamp;
  index index.html;

  location / {
    try_files $uri $uri.html $uri/ =404;
  }

  error_page 404 /404.html;
}
