server {
  include snippets/tls.conf;
  include snippets/docker_resolver.conf;
  server_name wiki.cybr.club;

  location / {
	include snippets/proxy_headers.conf;
    set $upstream outline;
    proxy_pass http://$upstream:9454;
  }
}
