server {
  include snippets/tls.conf;
  include snippets/docker_resolver.conf;
  server_name cybr.club www.cybr.club;

  location / {
    set $upstream website;
    proxy_pass http://$upstream:80;
  }
}